spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/to_do_management
    username: RafaRodrigues
    password: rafa123
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.mysql8dialect
    show-sql: true

mybatis:
  config-location: classpath:mybatis-config.xml
