spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.mysql8dialect
    show-sql: true
  rabbitmq:
    addresses: ${RABBITMQ_URI}

mybatis:
  config-location: classpath:mybatis-config.xml


queue:
  envio-email: ENVIO_EMAIL_QUEUE
